Refactor the honest scripts
david942j/honest pull request #7
Opened 2018-04-24 06:22 UTC by MedicineYeh

2018-04-24 06:59 UTC, david942j commented on libexec/honest-common.sh
> +###
Move this file to share/

2018-04-24 07:07 UTC, david942j commented on libexec/honest-clone
> +  [[ "$tag" != "" ]] && git checkout --detach "$tag" >/dev/null
I think it's ok to show the checking out message to users (no need >/dev/null)
Or maybe we can add silent/verbose options to control the logging level

2018-04-24 07:08 UTC, david942j commented on libexec/honest-clone
> +  cd $path
Same as the comment below

2018-04-24 07:10 UTC, david942j commented on libexec/honest-common.sh
> +get_hashed_name() {
`get_tmp_dir`

2018-04-24 08:40 UTC, MedicineYeh commented
>
/dev/null那是我延續你原本放在function那邊的，改成放到會有訊息的那兩行，這腳本因為是會被honest執行並且取回字串，所以兩邊還是要選一邊做啦，我當初改的時候還不是很確定要怎樣只是先把每項事物的影響層級盡量壓低，不要有在那一行看不出來的行為發生，例如我現在這樣放，平常debug時在function裡面echo就會有訊息印出來，不會不知道為什麼的沒訊息（原本做法是把redirection接在function
call）
不過說真的這還沒很確定要怎樣用，因為像是error
message也要能關靜音或者改用stderr不然honest呼叫honest-clone時有任何問題發生還是會導致回傳回來得字串除了path之外還有error
message，這樣rm -fr就會掛掉。

這部分是想說等跟你討論，你覺得呢？

On Tue, 24 Apr 2018 at 3:07 PM david942j <notifications@github.com> wrote:

> *@david942j* commented on this pull request.
> ------------------------------
>
> In libexec/honest-clone
> <https://github.com/david942j/honest/pull/7#discussion_r183623849>:
>
> > -  for (( i=0; i<=$n; i++ )); do
> -    if [[ ${url:$i:1} == '@' ]]; then
> -      REPO=${url:0:$i}
> -      TAG=${url:$i+1}
> -    fi
> -  done
> -  return 0
> +  local tag="$2"
> +  local path="$3"
> +  set -e
> +  # TODO Use shallow clone or other techniques to improve the speed
> +  git clone "$url" "$path" >/dev/null
> +  cd $path
> +  # if $tag is not present, checkout to the latest release.
> +  tag="${tag:-$(git describe --tags `git rev-list --tags --max-count=1 2>/dev/null` 2>/dev/null)}"
> +  [[ "$tag" != "" ]] && git checkout --detach "$tag" >/dev/null
>
> I think it's ok to show the checking out message to users (no need
> >/dev/null)
> Or maybe we can add silent/verbose options to control the logging level
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/david942j/honest/pull/7#pullrequestreview-114654631>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFxHiqZlwOGvilMsW3XslXlYHKXG-8vxks5trs8vgaJpZM4ThER9>
> .
>
-- 

Sincerely,
葉志威
Medicine Yeh
----
Department of Computer Science and Information Engineering
資訊工程系
National Taiwan University
國立台灣大學

NTUST Toastmasters
台科大國際英語演講社

2018-04-24 10:19 UTC, david942j commented
Let me take a look

2018-04-24 10:57 UTC, MedicineYeh commented
Your suggestions are adopted. Take a look.

2018-04-24 12:45 UTC, david942j commented
And please fix the failed tests as well

2018-04-24 16:07 UTC, david942j commented
For tests failed becuz of error message being changed, feel free to change the test scripts

2018-04-24 16:11 UTC, david942j commented
by running `bin/honest github:david942j/honest gem:meowaaa`,
`[ERROR] Fail on running 'honest-gem` is output
I think a nice error msg would be better.
(such as `Could not find a valid gem 'meowaaa' (>= 0) in any repository`)

2018-04-25 02:41 UTC, david942j commented
> /dev/null那是我延續你原本放在function那邊的，改成放到會有訊息的那兩行，這腳本因為是會被honest執行並且取回字串，所以兩邊還是要選一邊做啦，我當初改的時候還不是很確定要怎樣只是先把每項事物的影響層級盡量壓低，不要有在那一行看不出來的行為發生，例如我現在這樣放，平常debug時在function裡面echo就會有訊息印出來，不會不知道為什麼的沒訊息（原本做法是把redirection接在function
call）
不過說真的這還沒很確定要怎樣用，因為像是error
message也要能關靜音或者改用stderr不然honest呼叫honest-clone時有任何問題發生還是會導致回傳回來得字串除了path之外還有error
message，這樣rm -fr就會掛掉。
這部分是想說等跟你討論，你覺得呢？

How about let all logging functions `info/error/debug (maybe in the future)` output to stderr?
And use an env (e.g. `HONEST_LOGGING_LEVEL`) to control if the message should be printed

2018-04-25 06:11 UTC, MedicineYeh commented
All passed. Also, the log level feature is added and all the __log messages__ are now printed to stderr instead of stdout.

2018-04-25 07:06 UTC, david942j commented on share/honest/honest-common.sh
> +HONEST_LOGGING_LEVEL=${HONEST_LOGGING_LEVEL:-0}
set default value to be 1?
(let the default be no debug message)

2018-04-25 16:05 UTC, david942j commented
tests broken QQ

2018-04-25 16:31 UTC, david942j requested changes

2018-04-25 16:31 UTC, david942j commented on share/honest/honest-common.sh
> +# Set log level to stderr if not set. The number can be 0(any) - 5,
`Set log level to stderr if not set`
-> `Set log level to 1 if not set`

2018-04-25 16:31 UTC, david942j commented on libexec/honest
> +    (git --no-pager diff --no-index --diff-filter=M "$REPO_PATH" "$PACKAGE_PATH"/data)
`()` can be removed?

2018-04-25 16:31 UTC, david942j commented on libexec/honest-clone
> +#               Hide the all the output messages except for the name of temp directory
Hide all the output messages except the name of temp directory

2018-04-25 16:31 UTC, david942j commented on libexec/honest-clone
> +# When failed to convert the format, the original string will be return.
be returned

2018-04-25 16:31 UTC, david942j commented on libexec/honest-clone
> +# 'https://<author>@github.com/<authors>/<repo>@v1.00'.
use `@v1.0.0` as example would be better

2018-04-25 16:31 UTC, david942j commented on libexec/honest-clone
> +# 'https://<author>@github.com/<authors>/<repo>@v1.00'.
`<authors>/<repo>` -> `<author>/<repo>`

2018-04-25 16:31 UTC, david942j commented on libexec/honest-clone
> +#   <Repo> The repo name with format '<vendor>:<author>/<project>[@..]'
The format should be `http(s)://URL[@..]`

2018-04-25 16:31 UTC, david942j commented on libexec/honest-clone
> +QUITE_MODE="0"
Four typos in this file: `quite` -> `quiet`

2018-04-26 07:19 UTC, MedicineYeh commented
All fixed

2018-04-26 15:54 UTC, david942j commented on libexec/honest-clone
>  # The tag string will be 'v1.00' in this case.
1.0.0 XD

2018-04-26 15:55 UTC, david942j commented on libexec/honest-clone
>  # The tag string will be 'v1.00' in this case.
but consider the latest pr.. alright, forget this

2018-04-26 15:59 UTC, david942j approved these changes

2018-04-26 16:04 UTC, merged